### ISSUE TITLE
Webpage System

### ISSUE THREAD

**Issue by phiresky** [ML-KA/ML-KA.github.io#5]
Any particular reason to use Pelican?

[Jekyll](http://jekyllrb.com/) would have the benefit of github directly supporting it, so no need for the multiple branch stuff. (Running example: https://github.com/karpathy/karpathy.github.io )

I don't know anything about either of these two, except they use markdown and generate static pages.

**Comment by MartinThoma** [comment]
I use Jekyll for my website and I'm not very happy with it. It takes VERY much time to compile (see https://github.com/jekyll/jekyll/issues/1855)

In contrast, Pelican (currently, which is an unfair comparison) runs in a fraction of a second.

The multiple branch stuff is probably not necessary. I made this, because I thought it would be nice to separate generated pages from source files. I did the same thing with Jekyll.

But I don't know much about either of them. If you know more / have suggestions how to do better, they are always welcome :-)

**Comment by phiresky** [comment]
> jekyll/jekyll#1855

They got defensive real fast :D

> The multiple branch stuff is probably not necessary. I made this, because I thought it would be nice to separate generated pages from source files. I did the same thing with Jekyll.

Exactly, but afaik Github does that automatically, you just push the source to master and they automatically build it on their pages server.

**Comment by MartinThoma** [comment]
> They got defensive real fast :D

Indeed. Another reason to use Pelican is that I feel more comfortable with Python than with Ruby.
(see also: http://arunrocks.com/moving-blogs-to-pelican/#so-what-was-wrong-with-jekyll)

**Comment by phiresky** [comment]
It also seems like they implemented incremental page regeneration https://github.com/jekyll/jekyll/pull/3116 so shouldn't that mostly fix it?

**Comment by MartinThoma** [comment]
Yes, probably. But I still feel more comfortable with Python than with Ruby. If there isn't a reason for Jekyll, I would stick with Pelican.

**Comment by phiresky** [comment]
No, I guess it's fine as is.
